#!/bin/bash

if [ "@ATE_INSTALL_SERVER_SERVICE@" = "ON" ]; then
    systemctl enable vdp_ate_server
    systemctl start vdp_ate_server
fi

###############################################################
#                 MySQL database adjustments                  #
###############################################################

readonly MYSQL_ROOT_CREDENTIALS="-u root -pOhMyGodIamaRoot"
readonly ATE_DB=ate
readonly ATE_ICON_TABLE=icon_storage

#Clean test data/users/remote users from MySQL
mysql ${MYSQL_ROOT_CREDENTIALS} -e "DELETE FROM mysql.user WHERE User='';"
mysql ${MYSQL_ROOT_CREDENTIALS} -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
mysql ${MYSQL_ROOT_CREDENTIALS} -e "DELETE FROM mysql.db WHERE Db='test' or Db='test_%';"

#Create new users
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE USER 'reader'@'localhost' IDENTIFIED by 'JustCuriousWhatIsInside';
GRANT SELECT ON ate.* TO 'reader'@'localhost';FLUSH PRIVILEGES;"
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE USER 'tshmi'@'localhost' IDENTIFIED by 'JSIsaBestLanguageEverIsNot';
GRANT ALL PRIVILEGES ON ate.* TO 'tshmi'@'localhost';FLUSH PRIVILEGES;"
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE USER 'tdbc'@'localhost' IDENTIFIED by 'BestAppEverMadeByHumans';
GRANT ALL PRIVILEGES ON ate.* TO 'tdbc'@'localhost';FLUSH PRIVILEGES;"

#Create DB and Table
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE DATABASE IF NOT EXISTS ${ATE_DB};"
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE TABLE IF NOT EXISTS ${ATE_DB}.${ATE_ICON_TABLE}(
id INT(11) NOT NULL AUTO_INCREMENT,
sync_version VARCHAR(10) NOT NULL,
build_version VARCHAR(64) NOT NULL,
mode ENUM('DAY', 'NIGHT') NOT NULL,
name VARCHAR(128) NOT NULL,
image BLOB NOT NULL,
image_hash CHAR(32) NOT NULL,
image_center_x int NOT NULL,
image_center_y int NOT NULL,
image_top_left_x int DEFAULT NULL,
image_top_left_y int DEFAULT NULL,
image_bottom_right_x int DEFAULT NULL,
image_bottom_right_y int DEFAULT NULL,
parent_screen_resolution_x int DEFAULT NULL,
parent_screen_resolution_y int DEFAULT NULL,
parent_screen VARCHAR(64) DEFAULT NULL,
changed_by VARCHAR(32) NOT NULL,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT id_pk PRIMARY KEY (id));"

#Setup indexes
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE UNIQUE INDEX unique_fields_index ON 
${ATE_DB}.${ATE_ICON_TABLE} (sync_version, build_version, mode, name, image_hash, parent_screen);" #defines unique entry at table
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE INDEX sync_base_fields_index ON 
${ATE_DB}.${ATE_ICON_TABLE} (sync_version, build_version, mode);" #defines most common search set

#Setup triggers
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE TRIGGER ${ATE_DB}.${ATE_ICON_TABLE}_bi_tr 
BEFORE INSERT ON ${ATE_DB}.${ATE_ICON_TABLE} FOR EACH ROW 
SET NEW.changed_by = CURRENT_USER(), NEW.image_hash = MD5(NEW.image);" #defines user-initiator and timestamp update
mysql ${MYSQL_ROOT_CREDENTIALS} -e "CREATE TRIGGER ${ATE_DB}.${ATE_ICON_TABLE}_bu_tr 
BEFORE UPDATE ON ${ATE_DB}.${ATE_ICON_TABLE} FOR EACH ROW 
SET NEW.changed_by = CURRENT_USER(), NEW.image_hash = MD5(NEW.image);" #defines user-initiator and timestamp update
