#!/bin/bash

# Restore back-up of legacy Icon storage, if there is any
if [ -d @LEGACY_ICON_STORAGE_BAK@ ]; then
    echo "Restoring @LEGACY_ICON_STORAGE@ from back-up @LEGACY_ICON_STORAGE_BAK@..."
    mv -f @LEGACY_ICON_STORAGE_BAK@ @LEGACY_ICON_STORAGE@
fi

# Create and set permissions to writable data directory
mkdir -p @ATE_WRITABLE_DATA_PREFIX@

readonly USER=nvidia
readonly GROUP=nvidia
echo "Changing owner of @ATE_WRITABLE_DATA_PREFIX@ to ${USER}:${GROUP}..."
chown --recursive ${USER}:${GROUP} @ATE_WRITABLE_DATA_PREFIX@
test $? -eq 0 && echo "Ok" || echo "error: failed to set owner of @ATE_WRITABLE_DATA_PREFIX@ to ${USER}:${GROUP}"

readonly PERMISSIONS="a+rw"
echo "Changing permissions of @ATE_WRITABLE_DATA_PREFIX@ to ${PERMISSIONS}..."
chmod --recursive ${PERMISSIONS} @ATE_WRITABLE_DATA_PREFIX@
test $? -eq 0 && echo "Ok" || echo "error: failed to set permissions of @ATE_WRITABLE_DATA_PREFIX@ to ${PERMISSIONS}"

# Enable and start service if build is configured so
if [ "@ATE_INSTALL_SERVER_SERVICE@" = "ON" ]; then
    systemctl enable vdp_ate_server
    systemctl start vdp_ate_server
    test $? -eq 0 || echo "warning: systemctl start vdp_ate_server returned $?. See \"systemctl status vdp_ate_server\" and " \
                          "\"journalctl -xe -u vdp_ate_server\" for details. You may require to run vdp_ate_server service manually."
fi

# Ignore last command exit code
exit 0
