"""
Constants for icons and text
"""

"""ICONS"""


class Icons:
    A_C_ACTIVE = 'a_c_active'
    ACTIVE_AUDIO_BUTTON = 'audio_active'
    ACTIVE_CLIMATE_BUTTON = 'climate_on_off'
    ACTIVE_CLIMATE_PAGE_ICON = 'climate_active'
    ACTIVE_MOBILE_APPS_PAGE_BUTTON = 'apps_active'
    ACTIVE_PHONE_PAGE_BUTTON = 'phone_active'
    ACTIVE_SETTINGS_PAGE_BUTTON = 'settings_active'
    ADAPTIVE_VOLUME_MEDIUM_OPTION = 'medium'
    AUDIO_FREQUENCY_BUTTON = 'audio_frequency'
    BACK_BUTTON = 'back'
    BACK_PROPERTY = 'back_property_field'
    BALANCE_FADE_BUTTON = 'balance_fade'
    BLUETOOTH_SWITCH_ON_BUTTON = 'switch_on'
    CHECKED_SETTINGS_NAVIGATION_CHECKBOX_BUTTON = 'checkbox_checked'
    CHIMES_ICON = 'guidance_prompts_chimes_active'
    CLIMATE_ARROW_DOWN = 'climate_down'
    CLIMATE_ARROW_UP = 'climate_up'
    CLIMATE_AUTO_BUTTON = 'AUTO'
    CLIMATE_DEFROST_BUTTON = 'defrost'
    CLIMATE_ON_OFF_BUTTON = 'climate_on_off'
    CLOCK_SETTINGS_12H = 'time_12h_format'
    CLOCK_SETTINGS_24H = 'time_24h_format'
    CLOCK_SWITCH_OFF = 'switch_off'
    CLOSE_BUTTON = 'close'
    DEFROST = 'defrost'
    DOWN_AIRFLOW_ACTIVE_BUTTON = 'down_airflow_active'
    DOWN_AIRFLOW_BUTTON = 'down_airflow'
    DOWN_ARROW_SMALL = 'down_arrow_small'
    DOWN_SCROLL_BUTTON_ACTIVE = 'down_active'
    DOWN_SCROLL_BUTTON_INACTIVE = 'down_inactive'
    ENTER_BUTTON_IN_SET_FREQUENCY = 'enter_active'
    EXCLAMATION_ICON = 'exclamation_icon'
    FIND_MOBILE_APPS_BUTTON = 'find_mobile_apps'
    FRONT_HEATING = 'front_heating'
    HOME_PAGE_ICON = 'home'
    INACTIVE_AUDIO_PAGE_BUTTON = 'audio'
    INACTIVE_CLIMATE_PAGE_ICON = 'climate'
    INACTIVE_MOBILE_APPS_PAGE_BUTTON = 'apps'
    INACTIVE_NAVIGATION_PAGE_BUTTON = 'nav'
    INACTIVE_PHONE_PAGE_BUTTON = 'phone'
    INACTIVE_SETTINGS_PAGE_BUTTON = 'settings'
    INFORMATION_DIALOG_BUTTON = 'information'
    MAX_FRONT_HEATING_INACTIVE = 'max_front_heating_inactive'
    MOBILE_APPS_BUTTON = 'mobile_apps'
    MOBILE_BLUETOOTH_BUTTON = 'bluetooth'
    PHONE_CONNECT_TO = 'connect_to'
    PLUS_ICON = 'guidance_prompts_plus'
    PLUS_ICON_ACTIVE = 'guidance_prompts_plus_active'
    PRESETS_BUTTON = 'presets'
    REAR_HEATING = 'rear_heating'
    SCROLL = 'scroll'
    SETTINGS_CLOCK_BUTTON = 'clock'
    SETTINGS_GENERAL_BUTTON = 'settings_general_button'
    SETTINGS_NAVIGATION_BUTTON = 'settings_navigation'
    SETTINGS_RADIO_BUTTON = 'radio'
    SETTINGS_SOUND_BUTTON = 'settings_sound'
    SIRIUSXM_BUTTON = 'siriusxm'
    SLIDER = 'slider'
    SOUND_RESET_ALL_BUTTON = 'reset_all'
    SYNC_CONNECT_BUTTON = 'sync_connect'
    TOP_AIRFLOW_ACTIVE_BUTTON = 'top_airflow_active'
    TOP_AIRFLOW_BUTTON = 'top_airflow'
    UNCHECKED_SETTINGS_NAVIGATION_CHECKBOX_BUTTON = 'checkbox_unchecked'
    UP_SCROLL_BUTTON_INACTIVE = 'up_inactive'
    VOICE_ICON = 'guidance_prompts_voice'
    VOICE_ICON_ACTIVE = 'guidance_prompts_voice_active'


class Text:
    ADAPTIVE_VOLUME_TEXT = 'Adaptive volume'
    ADD_BLUETOOTH_DEVICE_TEXT = 'Add a Bluetooth device'
    ALL_SEATS_TEXT = 'All seats'
    ALWAYS_USE_FASTEST_ROUTE_TEXT = 'Always use Fastest route'
    AUTO_TEXT = 'AUTO'
    AVOID_FERRIES_CAR_TRAINS_TEXT = 'Avoid ferries/car trains'
    AVOID_MOTORWAYS_TEXT = 'Avoid motorways'
    AVOID_TOLL_ROADS_TEXT = 'Avoid toll roads'
    BLUETOOTH_SETTINGS_TEXT = 'Bluetooth settings'
    BLUETOOTH_VIEW_DEVICES_TEXT = 'View devices'
    BREADCRUMBS = 'Breadcrumbs'
    CHIMES_ONLY_TEXT = 'Chimes only'
    CITY_MODEL_TEXT = '3D city model'
    CLOCK_AUTO_TIME_ZONE_TEXT = 'Auto time zone update'
    CLOCK_FORMAT_TEXT = 'Clock format'
    CLOCK_PM_PERIOD_TEXT = 'PM'
    CLOCK_RESET_GPS_TEXT = 'Reset clock to GPS time'
    CLOCK_SETTINGS_TITLE_TEXT = 'Clock settings'
    CONNECT_A_DEVICE_TEXT = 'Connect a device'
    DEFROST_CONTROLS_TEXT = 'Defrost controls'
    DSP_OCCUPANCY_TEXT = 'DSP occupancy'
    DUAL_TEXT = 'DUAL'
    DYNAMIC_ROUTE_GUIDANCE_TEXT = 'Dynamic route guidance'
    ECO_TIME_PENALTY_TEXT = 'Eco time penalty'
    FIND_MOBILE_APPS_TEXT = 'Find'
    FIND_PARKING_AUTOMATICALLY_TEXT = 'Find parking automatically'
    GUIDANCE_PROMPTS_TEXT = 'Guidance prompts'
    MAP_PREFERENCES_TEXT = 'Map preferences'
    NAVIGATION_FAULT_TEXT = 'fault'
    NAVIGATION_PREFERENCES_TEXT = 'Navigation preferences'
    NAVIGATION_SETTINGS_TEXT = 'Navigation settings'
    PAIR_PHONE_TEXT = 'Pair phone'
    PREFERRED_ROUTE_TEXT = 'Preferred route'
    RADIO_AUTOSTORE_PRESETS_TEXT = 'Autostore presets (AST)'
    RADIO_REFRESH_TEXT = 'Refresh'
    RADIO_SETTINGS_TEXT = 'Radio settings'
    RADIO_TEXT = 'RadioText'
    ROUTE_PREFERENCES_TEXT = 'Route preferences'
    SIRIUS_XM_TRAVEL_LINK_TEXT = 'SiriusXM Travel'
    SOUND_SETTINGS_TITLE_TEXT = 'Sound settings'
    SOUND_TREBLE_TEXT = 'Treble'
    SOURCES_TEXT = 'Sources'
    VOICE_CHIMES_TEXT = 'Voice & chimes'
    VOICE_ONLY_TEXT = 'Voice only'


"""JIRA"""
TASK_LINK = 'https://adc.luxoft.com/jira/browse/{}'
