"""
Constants for icons and text
"""

"""ICONS"""


class Icons:
    A_C_ACTIVE = 'a_c_active'
    ACTIVE_AUDIO_BUTTON = 'audio_active'
    ACTIVE_CLIMATE_BUTTON = 'climate_on_off'
    ACTIVE_CLIMATE_PAGE_ICON = 'climate_active'
    ACTIVE_MOBILE_APPS_PAGE_BUTTON = 'apps_active'
    ACTIVE_PHONE_PAGE_BUTTON = 'phone_active'
    ACTIVE_SETTINGS_PAGE_BUTTON = 'settings_active'
    ADAPTIVE_VOLUME_MEDIUM_OPTION = 'medium'
    AUDIO_FREQUENCY_BUTTON = 'audio_frequency'
    AUDIO_FM_SOURCE_BUTTON = 'audio_fm_sources_button'
    AUDIO_SIRIUS_SOURCES_BUTTON = 'audio_sirius_sources_button'
    BACK_BUTTON = 'back'
    BACK_PROPERTY = 'back_property_field'
    BALANCE_FADE_BUTTON = 'balance_fade'
    BLUETOOTH_SWITCH_ON_BUTTON = 'switch_on'
    CHECKED_SETTINGS_NAVIGATION_CHECKBOX_BUTTON = 'checkbox_checked'
    CHIMES_ICON = 'guidance_prompts_chimes_active'
    CLIMATE_ARROW_DOWN = 'climate_down'
    CLIMATE_ARROW_UP = 'climate_up'
    CLIMATE_AUTO_BUTTON = 'AUTO'
    CLIMATE_DEFROST_BUTTON = 'defrost'
    CLIMATE_ON_OFF_BUTTON = 'climate_on_off'
    CLOCK_SETTINGS_12H = 'time_12h_format'
    CLOCK_SETTINGS_24H = 'time_24h_format'
    CLOCK_SWITCH_OFF = 'switch_off'
    CLOSE_BUTTON = 'close'
    DEFROST = 'defrost'
    DOWN_AIRFLOW_ACTIVE_BUTTON = 'down_airflow_active'
    DOWN_AIRFLOW_BUTTON = 'down_airflow'
    DOWN_ARROW_SMALL = 'down_arrow_small'
    DOWN_SCROLL_BUTTON_ACTIVE = 'down_active'
    DOWN_SCROLL_BUTTON_INACTIVE = 'down_inactive'
    ENTER_BUTTON_IN_SET_FREQUENCY = 'enter_active'
    EXCLAMATION_ICON = 'exclamation_icon'
    FIND_MOBILE_APPS_BUTTON = 'find_mobile_apps'
    FRONT_HEATING = 'front_heating'
    HOME_PAGE_ICON = 'home'
    HOME_SIRIUS_ICON = 'home_sirius_icon'
    INACTIVE_AUDIO_PAGE_BUTTON = 'audio'
    INACTIVE_CLIMATE_PAGE_ICON = 'climate'
    INACTIVE_MOBILE_APPS_PAGE_BUTTON = 'apps'
    INACTIVE_NAVIGATION_PAGE_BUTTON = 'nav'
    INACTIVE_PHONE_PAGE_BUTTON = 'phone'
    INACTIVE_SETTINGS_PAGE_BUTTON = 'settings'
    INFORMATION_DIALOG_BUTTON = 'information'
    MAX_FRONT_HEATING_INACTIVE = 'max_front_heating_inactive'
    MOBILE_APPS_BUTTON = 'mobile_apps'
    MOBILE_BLUETOOTH_BUTTON = 'bluetooth'
    PHONE_CONNECT_TO = 'connect_to'
    PLUS_ICON = 'guidance_prompts_plus'
    PLUS_ICON_ACTIVE = 'guidance_prompts_plus_active'
    PRESETS_BUTTON = 'presets'
    REAR_HEATING = 'rear_heating'
    SCROLL = 'scroll'
    SETTINGS_CLOCK_BUTTON = 'clock'
    SETTINGS_GENERAL_BUTTON = 'settings_general_button'
    SETTINGS_NAVIGATION_BUTTON = 'settings_navigation'
    SETTINGS_RADIO_BUTTON = 'radio'
    SETTINGS_SOUND_BUTTON = 'settings_sound'
    SIRIUSXM_BUTTON = 'siriusxm'
    SLIDER = 'slider'
    SOUND_RESET_ALL_BUTTON = 'reset_all'
    SYNC_CONNECT_BUTTON = 'sync_connect'
    TOP_AIRFLOW_ACTIVE_BUTTON = 'top_airflow_active'
    TOP_AIRFLOW_BUTTON = 'top_airflow'
    UNCHECKED_SETTINGS_NAVIGATION_CHECKBOX_BUTTON = 'checkbox_unchecked'
    UP_SCROLL_BUTTON_INACTIVE = 'up_inactive'
    VOICE_ICON = 'guidance_prompts_voice'
    VOICE_ICON_ACTIVE = 'guidance_prompts_voice_active'


class Text:
    ADAPTIVE_VOLUME_TEXT = 'Adaptive volume'
    ADD_BLUETOOTH_DEVICE_TEXT = 'Add a Bluetooth device'
    ALL_SEATS_TEXT = 'All seats'
    ALWAYS_USE_FASTEST_ROUTE_TEXT = 'Always use Fastest route'
    AUDIO_ALERT_TEXT = 'Alert'
    AUDIO_BLUETOOTH_AUDIO_TEXT = 'Bluetooth audio'
    AUDIO_BUTTON_PANEL_TEXT = 'Audio'
    AUDIO_CD_TEXT = 'CD'
    AUDIO_CHANNEL_GUIDE_TEXT = 'Channel guide'
    AUDIO_CLASSIC_VINYL_TEXT = 'Classic Vinyl'
    AUDIO_CLSVINYL_TEXT = 'ClsVinyl'
    AUDIO_DIRECT_TUNE_1 = '1'
    AUDIO_DIRECT_TUNE_2 = '2'
    AUDIO_DIRECT_TUNE_3 = '3'
    AUDIO_DIRECT_TUNE_4 = '4'
    AUDIO_DIRECT_TUNE_5 = '5'
    AUDIO_DIRECT_TUNE_6 = '6'
    AUDIO_DIRECT_TUNE_7 = '7'
    AUDIO_DIRECT_TUNE_8 = '8'
    AUDIO_DIRECT_TUNE_9 = '9'
    AUDIO_DIRECT_TUNE_0 = '0'
    AUDIO_DIRECT_TUNE_CANCEL = 'Cancel'
    AUDIO_DIRECT_TUNE_ENTER = 'Enter'
    AUDIO_DIRECT_TUNE_TEXT = 'Direct tune'
    AUDIO_FM_TEXT = 'FM'
    AUDIO_AM_TEXT = 'AM'
    AUDIO_FREQUENCY_107_9_Mhz = '107.9 MHz'
    AUDIO_FREQUENCY_1710 = '1710'
    AUDIO_FREQUENCY_TEXT = 'Frequency'
    AUDIO_HIGHWAY_TEXT = 'Highway'
    AUDIO_PRESETS_TEXT = 'Presets'
    AUDIO_REPLAY_TEXT = 'Replay'
    AUDIO_ROCK_TEXT = 'Rock'
    AUDIO_SIRIUSXM_TEXT = 'SiriusXM'
    AUTO_TEXT = 'AUTO'
    AVOID_FERRIES_CAR_TRAINS_TEXT = 'Avoid ferries/car trains'
    AVOID_MOTORWAYS_TEXT = 'Avoid motorways'
    AVOID_TOLL_ROADS_TEXT = 'Avoid toll roads'
    BLUETOOTH_SETTINGS_TEXT = 'Bluetooth settings'
    BLUETOOTH_VIEW_DEVICES_TEXT = 'View devices'
    BREADCRUMBS = 'Breadcrumbs'
    CANCEL = 'Cancel'
    CHIMES_ONLY_TEXT = 'Chimes only'
    CITY_MODEL_TEXT = '3D city model'
    CLIMATE_BUTTON_PANEL_TEXT = 'Climate'
    CLOCK_AUTO_TIME_ZONE_TEXT = 'Auto time zone update'
    CLOCK_FORMAT_TEXT = 'Clock format'
    CLOCK_PM_PERIOD_TEXT = 'PM'
    CLOCK_RESET_GPS_TEXT = 'Reset clock to GPS time'
    CLOCK_SETTINGS_TITLE_TEXT = 'Clock settings'
    CONNECT_A_DEVICE_TEXT = 'Connect a device'
    CONNECT_A_PHONE_TEXT = 'Add device'
    DEFROST_CONTROLS_TEXT = 'Defrost controls'
    DSP_OCCUPANCY_TEXT = 'DSP occupancy'
    DUAL_TEXT = 'DUAL'
    DYNAMIC_ROUTE_GUIDANCE_TEXT = 'Dynamic route guidance'
    ECO_TIME_PENALTY_TEXT = 'Eco time penalty'
    HOME_FM_TEXT = 'FM'
    HOME_SIRIUS_TEXT = 'SIRIUS'
    FIND_MOBILE_APPS_TEXT = 'Find'
    FIND_PARKING_AUTOMATICALLY_TEXT = 'Find parking automatically'
    GUIDANCE_PROMPTS_TEXT = 'Guidance prompts'
    MAP_PREFERENCES_TEXT = 'Map preferences'
    MOBILE_APPS_BUTTON_PANEL_TEXT = 'Mobile apps'
    NAVIGATION_BUTTON_PANEL_TEXT = 'Navigation'
    NAVIGATION_FAULT_TEXT = 'Navigation fault'
    NAVIGATION_PREFERENCES_TEXT = 'Navigation preferences'
    NAVIGATION_SETTINGS_TEXT = 'Navigation settings'
    PAIR_PHONE_TEXT = 'Pair phone'
    PHONE_BUTTON_PANEL_TEXT = 'Phone'
    PREFERRED_ROUTE_TEXT = 'Preferred route'
    RADIO_AUTOSTORE_PRESETS_TEXT = 'Autostore presets (AST)'
    RADIO_REFRESH_TEXT = 'Refresh'
    RADIO_SETTINGS_TEXT = 'Radio settings'
    RADIO_TEXT = 'RadioText'
    ROUTE_PREFERENCES_TEXT = 'Route preferences'
    SETTINGS_BUTTON_PANEL_TEXT = 'Settings'
    SIRIUS_XM_TRAVEL_LINK_TEXT = 'SiriusXM Travel'
    SOUND_SETTINGS_TITLE_TEXT = 'Sound settings'
    SOUND_TREBLE_TEXT = 'Treble'
    SOURCES_TEXT = 'Sources'
    VOICE_CHIMES_TEXT = 'Voice & chimes'
    VOICE_ONLY_TEXT = 'Voice only'


"""DATA FOR PARAMETERIZATION"""

# home page
home_page_text = [Text.CONNECT_A_PHONE_TEXT, Text.NAVIGATION_FAULT_TEXT, Text.AUDIO_BUTTON_PANEL_TEXT,
                  Text.CLIMATE_BUTTON_PANEL_TEXT, Text.PHONE_BUTTON_PANEL_TEXT, Text.NAVIGATION_BUTTON_PANEL_TEXT,
                  Text.MOBILE_APPS_BUTTON_PANEL_TEXT, Text.SETTINGS_BUTTON_PANEL_TEXT]

audio_page_text = [Text.SOURCES_TEXT, Text.AUDIO_FREQUENCY_TEXT, Text.AUDIO_PRESETS_TEXT,
                   Text.AUDIO_FREQUENCY_107_9_Mhz, ]

audio_sources_page_text = [Text.AUDIO_AM_TEXT, Text.AUDIO_FM_TEXT, Text.AUDIO_SIRIUSXM_TEXT,
                           Text.AUDIO_CD_TEXT, Text.AUDIO_BLUETOOTH_AUDIO_TEXT]

audio_sirius_page_text = [Text.AUDIO_CLSVINYL_TEXT, Text.AUDIO_CLASSIC_VINYL_TEXT, Text.AUDIO_ROCK_TEXT,
                          Text.AUDIO_CHANNEL_GUIDE_TEXT, Text.AUDIO_DIRECT_TUNE_TEXT, Text.AUDIO_REPLAY_TEXT,
                          Text.AUDIO_ALERT_TEXT]
audio_direct_tune_text = [Text.AUDIO_DIRECT_TUNE_1, Text.AUDIO_DIRECT_TUNE_2, Text.AUDIO_DIRECT_TUNE_3,
                          Text.AUDIO_DIRECT_TUNE_4, Text.AUDIO_DIRECT_TUNE_5, Text.AUDIO_DIRECT_TUNE_6,
                          Text.AUDIO_DIRECT_TUNE_7, Text.AUDIO_DIRECT_TUNE_8, Text.AUDIO_DIRECT_TUNE_9,
                          Text.AUDIO_DIRECT_TUNE_0, Text.AUDIO_DIRECT_TUNE_CANCEL, Text.AUDIO_DIRECT_TUNE_ENTER]

"""JIRA"""
TASK_LINK = 'https://adc.luxoft.com/jira/browse/{}'
