"""
Constants for icons and text for Menlo
"""


class Icons:
    # GENERAL
    GENERAL_ARROW_DOWN = 'general_arrow_down'
    GENERAL_ARROW_DOWN_DISABLED = 'general_arrow_down_disabled'
    GENERAL_ARROW_LEFT = 'general_arrow_left'
    GENERAL_ARROW_RIGHT = 'general_arrow_right'
    GENERAL_ARROW_UP = 'general_arrow_up'
    GENERAL_ARROW_UP_ACTIVE = 'general_arrow_up_active'
    GENERAL_CHECKBOX_ACTIVE = 'general_checkbox_active'
    GENERAL_CHECKBOX_INACTIVE = 'general_checkbox_inactive'
    GENERAL_DRAWER_HANDLE = 'general_drawer_handle'
    GENERAL_INFO = 'general_info'
    GENERAL_TOGLE_ACTIVE = 'general_togle_active'
    GENERAL_TOGLE_INACTIVE = 'general_togle_inactive'
    GENERAL_MAXIMIZE_APP_BUTTON = 'general_maximize_app_button'

    # MAIN
    MAIN_APPS_BUTTON_ACTIVE = "main_apps_button_active"
    MAIN_APPS_BUTTON_INACTIVE = "main_apps_button_inactive"
    MAIN_CLIMATE_EXTENDED_BUTTON_INACTIVE = "main_climate_extended_button_inactive"
    MAIN_FAN_INACTIVE = "main_fan_inactive"
    MAIN_HEAT_WINDSHIELD = "main_heat_windshield"
    MAIN_MINUS_BUTTON = "main_minus_button"
    MAIN_PLUS_BUTTON = "main_plus_button"
    MAIN_R_HEAT_INACTIVE = "main_r_heat_inactive"
    MAIN_SETTINGS_CONTROLS_BUTTON_ACTIVE = "main_settings_controls_button_active"
    MAIN_SETTINGS_CONTROLS_BUTTON_INACTIVE = "main_settings_controls_button_inactive"
    MAIN_VOL_ON_OFF = "main_vol_on_off"

    # APPS
    APPS_BLUETOOTH_STEREO_BUTTON = "apps_bluetooth_stereo_button"
    APPS_OWNERS_MANUAL_BUTTON = "apps_owners_manual_button"
    APPS_PHONE_BUTTON = "apps_phone_button"
    APPS_RADIO_BUTTON = "apps_radio_button"
    APPS_SEATBELT_BUTTON = "apps_seatbelt_button"
    APPS_TIRE_PRESSURE_BUTTON = "apps_tire_pressure_button"
    APPS_TRIP_IOD_BUTTON = "apps_trip_iod_button"

    # TIRE PRESSURE APP
    TIRE_PRESSURE_APP_TITLE_ICON = 'tire_pressure_app_title_icon'

    # TRIP IOD APP
    TRIP_IOD_APP_BATTERY_ICON = 'trip_iod_app_battery_icon'
    TRIP_IOD_APP_TIMER_ICON = 'trip_iod_app_timer_icon'
    TRIP_IOD_APP_TITLE_ICON = 'trip_iod_app_title_icon'

    # RADIO APP
    RADIO_AM_SOURCE_BUTTON = 'radio_am_source_button'
    RADIO_FM_SOURCE_BUTTON = 'radio_fm_source_button'
    RADIO_SIRIUSXM_SOURCE_BUTTON = 'radio_siriusxm_source_button'
    RADIO_MANUAL_TUNE_BUTTON = 'radio_manual_tune_button'
    RADIO_SEEK_LEFT_BUTTON = 'radio_seek_left_button'
    RADIO_SEEK_RIGHT_BUTTON = 'radio_seek_right_button'
    RADIO_SETTINGS_BUTTON = 'radio_settings_button'
    RADIO_MINUS_BUTTON = 'radio_minus_button'
    RADIO_PLUS_BUTTON = 'radio_plus_button'

    # SETTINGS
    SETTINGS_SOUND_BUTTON = 'settings_sound_button'
    SETTINGS_CLOCK_BUTTON = 'settings_clock_button'
    SETTINGS_PHONE_LIST_BUTTON = 'settings_phone_list_button'
    SETTINGS_CONNECTIVITY_BUTTON = 'settings_connectivity_button'
    SETTINGS_RADIO_BUTTON = 'settings_radio_button'
    SETTINGS_DRIVER_ASSISTANCE_BUTTON = 'settings_driver_assistance_button'
    SETTINGS_VEHICLE_BUTTON = 'settings_vehicle_button'
    SETTINGS_GENERAL_BUTTON = 'settings_general_button'
    SETTINGS_SYSTEM_UPDATES_BUTTON = 'settings_system_updates_button'
    SETTINGS_DISPLAY_BUTTON = 'settings_display_button'

    # SETTINGS CLOCK
    SETTINGS_CLOCK_AM_BUTTON_ACTIVE = 'settings_clock_am_button_active'
    SETTINGS_CLOCK_PM_BUTTON_INACTIVE = 'settings_clock_pm_button_inactive'

    # SETTINGS PHONE LIST
    SETTINGS_PHONE_LIST_ADD_PHONE_BUTTON = 'settings_phone_list_add_phone_button'


class Text:
    # GENERAL
    RESET_TEXT = 'Reset'
    OFF_TEXT = 'Off'

    # MAIN
    MAIN_AUTO_TEXT = 'AUTO'
    MAIN_VOL_TEXT = 'VOL'
    MAIN_MAX_TEXT = 'MAX'

    # APPS
    APPS_RADIO_TEXT = 'Radio'
    APPS_PHONE_TEXT = 'Phone'
    APPS_TIRE_PRESSURE_TEXT = 'Tire'
    APPS_TRIP_IOD_TEXT = 'Trip IOD'
    APPS_SEATBELT_TEXT = 'Seatbelt'
    APPS_BLUETOOTH_STEREO_TEXT = 'Bluetooth'
    APPS_OWNERS_MANUAL_TEXT = 'Manual'

    # TIRE PRESSURE APP
    TIRE_PRESSURE_APP_TITLE_TEXT = 'Tyre pressure (psi)'
    TIRE_PRESSURE_APP_DEFAULT_VALUE_TEXT = '36'

    # TRIP IOD APP
    TRIP_IOD_APP_TITLE_TEXT = 'This trip'
    TRIP_IOD_APP_TRIP_COMPUTER_1_TAB_TEXT = 'Trip computer 1'
    TRIP_IOD_APP_TRIP_COMPUTER_2_TAB_TEXT = 'Trip computer 2'
    TRIP_IOD_APP_INACTIVE_TEXT = 'Inactive'
    TRIP_IOD_APP_TIME_SECONDS_DEFAULT_TEXT = '00:00:00 seconds'
    TRIP_IOD_APP_WHERE_ENERGY_GOES_TEST = 'Where did my energy go?'
    TRIP_IOD_APP_CLIMATE_USE_TEXT = 'Climate use'
    TRIP_IOD_APP_ROUTE_TEXT = 'Route'
    TRIP_IOD_APP_ACCESSORIES_TEXT = 'Accessories'
    TRIP_IOD_APP_EXT_TEMP_TEXT = 'Ext. Temp.'
    TRIP_IOD_APP_NONE_PERCENTAGE_TEXT = '--%'

    # RADIO APP
    RADIO_PRESET_TEXT = 'Preset'
    RADIO_AM_TEXT = 'AM'
    RADIO_FM_TEXT = 'FM'
    RADIO_SIRIUSXM_TEXT = 'SiriusXM'

    # CONTROLS/SETTINGS
    CONTROLS_TAB_TITLE_TEXT = 'CONTROLS'
    SETTINGS_TAB_TITLE_TEXT = 'SETTINGS'

    # SETTINGS
    SETTINGS_SOUND_BUTTON_TEXT = 'Sound'
    SETTINGS_CLOCK_BUTTON_TEXT = 'Clock'
    SETTINGS_PHONE_LIST_BUTTON_TEXT = 'Phone List'
    SETTINGS_CONNECTIVITY_BUTTON_TEXT = 'Connectivity'
    SETTINGS_RADIO_BUTTON_TEXT = 'Radio'
    SETTINGS_DRIVER_ASSISTANCE_BUTTON_TEXT = 'Driver'
    SETTINGS_VEHICLE_BUTTON_TEXT = 'Vehicle'
    SETTINGS_GENERAL_BUTTON_TEXT = 'General'
    SETTINGS_SYSTEM_UPDATES_BUTTON_TEXT = 'System'
    SETTINGS_MOBILE_APPS_BUTTON_TEXT = 'Mobile Apps'
    SETTINGS_DISPLAY_BUTTON_TEXT = 'Display'

    # SETTINGS SOUND
    SETTINGS_SOUND_TITLE_TEXT = 'SOUND'
    SETTINGS_SOUND_TONE_TEXT = 'Tone Settings'
    SETTINGS_SOUND_BALANCE_FADE_TEXT = 'Balance/Fade'
    SETTINGS_SOUND_DSP_OCCUPANCY_TEXT = 'DSP Occupancy:'
    SETTINGS_SOUND_DSP_ALL_SEATS_TEXT = 'All Seats'

    # SETTINGS CLOCK
    SETTINGS_CLOCK_TITLE_TEXT = 'CLOCK'
    SETTINGS_CLOCK_MODE_TEXT = '24-hour Mode'
    SETTINGS_CLOCK_TIME_ZONE_TEXT = 'Automatic Time Zone Update'

    # SETTINGS PHONE LIST
    SETTINGS_PHONE_LIST_TITLE_TEXT = 'PHONE LIST'
    SETTINGS_PHONE_LIST_ADD_PHONE_TEXT = 'Add Phone'

    # SETTINGS CONNECTIVITY
    SETTINGS_CONNECTIVITY_TITLE_TEXT = 'CONNECTIVITY'
    SETTINGS_CONNECTIVITY_FEATURES_TEXT = 'Connected Vehicle Features'
    SETTINGS_CONNECTIVITY_BLUETOOTH_TEXT = 'Bluetooth'
    SETTINGS_CONNECTIVITY_PROJECTION_TEXT = 'Wireless App Projection'
    SETTINGS_CONNECTIVITY_NETWORKS_TEXT = 'Manage Wi-Fi Networks'

    # SETTINGS RADIO
    SETTINGS_RADIO_TITLE_TEXT = 'RADIO'
    SETTINGS_RADIO_PRESET_ROWS_TEXT = 'Preset Rows:'
    SETTINGS_RADIO_AM_HD_RADIO_TEXT = 'AM HD Radio'

    # SETTINGS DRIVER ASSISTANCE
    SETTINGS_DRIVER_ASSISTANCE_TITLE_TEXT = 'DRIVER ASSISTANCE'
    SETTINGS_DRIVER_ASSISTANCE_CRUISE_CONTROL_TEXT = 'Cruise Control:'
    SETTINGS_DRIVER_ASSISTANCE_SPEED_LIMIT_ASSIST_TEXT = 'Speed Limit Assist'
    SETTINGS_DRIVER_ASSISTANCE_LANE_KEEPING_SYSTEMS_TEXT = 'Lane-Keeping System'
    SETTINGS_DRIVER_ASSISTANCE_PRE_COLLISION_ASSIST_TEXT = 'Pre-Collision Assist'
    SETTINGS_DRIVER_ASSISTANCE_REAR_VIEW_CAMERA_DELAY_TEXT = 'Rear View Camera Delay'
    SETTINGS_DRIVER_ASSISTANCE_GRADE_ASSIST_TEXT = 'Grade Assist'
    SETTINGS_DRIVER_ASSISTANCE_HILL_DESCENT_CONTROL_TEXT = 'Hill Descent Control'
    SETTINGS_DRIVER_ASSISTANCE_WRONG_WAY_ALERT_TEXT = 'Wrong Way Alert'
    SETTINGS_DRIVER_ASSISTANCE_DRIVER_ALERT_TEXT = 'Driver Assist'
    SETTINGS_DRIVER_ASSISTANCE_HILL_START_ASSIST_TEXT = 'Hill Start Assist'
    SETTINGS_DRIVER_ASSISTANCE_AUTO_START_STOP_TEXT = 'Auto StartStop'
    SETTINGS_DRIVER_ASSISTANCE_YOU_ARE_USING_A_MYKEY_TEXT = 'You are using a MyKey.'
    SETTINGS_DRIVER_ASSISTANCE_CLOSE_BUTTON_TEXT = 'Close'

    # SETTINGS VEHICLE
    SETTINGS_VEHICLE_TITLE_TEXT = 'VEHICLE'
    SETTINGS_VEHICLE_VEHICLE_POWER_DOWN_TIMER = 'Vehicle Power Down Timer'
    SETTINGS_VEHICLE_EASY_ENTRY_EXIT_TEXT = 'Easy Entry/Exit'
    SETTINGS_VEHICLE_PARK_LOCK_CONTROL_TEXT = 'Park Lock Control'
    SETTINGS_VEHICLE_SILENT_MODE_TEXT = 'Silent Mode'
    SETTINGS_VEHICLE_MYKEY_TEXT = 'MyKey'
    SETTINGS_VEHICLE_ONBOARD_MODEM_SERIAL_NUMBER_TEXT = 'Onboard Modem Serial Number'
    SETTINGS_VEHICLE_ALARM_SYSTEM_TEXT = 'Alarm System'
    SETTINGS_VEHICLE_CHIMES_TEXT = 'Chimes'
    SETTINGS_VEHICLE_REMOTE_START_SETUP_TEXT = 'Remote Start Setup'
    SETTINGS_VEHICLE_WINDOWS_TEXT = 'Windows'
    SETTINGS_VEHICLE_WIPERS_TEXT = 'Wipers'

    # SETTINGS GENERAL
    SETTINGS_GENERAL_TITLE_TEXT = 'GENERAL'
    SETTINGS_GENERAL_LANGUAGE_TEXT = 'Language:'
    SETTINGS_GENERAL_LANG_ENGLISH_US_TEXT = 'English - US'
    SETTINGS_GENERAL_TEMPERATURE_UNITS_TEXT = 'Temperature Units:'
    SETTINGS_GENERAL_TEMP_CELSIUS_TEXT = 'Celsius'
    SETTINGS_GENERAL_MEASUREMENT_UNITS_TEXT = 'Measurement Units:'
    SETTINGS_GENERAL_MEASUR_MILES_AND_MPG_TEXT = 'Miles & MPG'
    SETTINGS_GENERAL_TIRE_PRESSURE_UNITS_TEXT = 'Tire Pressure Units:'
    SETTINGS_GENERAL_TIRE_PRESSURE_PSI_TEXT = 'psi'
    SETTINGS_GENERAL_TOUCHSCREEN_BEEP_TEXT = 'Touchscreen Beep'
    SETTINGS_GENERAL_ABOUT_SYNC_TEXT = 'About SYNC'
    SETTINGS_GENERAL_SOFTWARE_LICENSES_TEXT = 'Software Licenses'
    SETTINGS_GENERAL_SUBMIT_FEEDBACK_TEXT = 'Submit Feedback'
    SETTINGS_GENERAL_RESET_TEXT = 'Reset'

    # SYSTEM UPDATES
    SETTINGS_SYSTEM_UPDATES_TITLE_TEXT = 'SYSTEM UPDATES'
    SETTINGS_SYSTEM_UPDATES_AUTOMATIC_UPDATES_TEXT = 'Automatic Updates'
    SETTINGS_SYSTEM_UPDATES_NOTIFICATIONS_TEXT = 'Notifications'
    SETTINGS_SYSTEM_UPDATES_SCHEDULE_UPDATES_TEXT = 'Schedule updates'
    SETTINGS_SYSTEM_UPDATES_UPDATE_DETAILS_TEXT = 'Update Details'

    # SETTINGS DISPLAY
    SETTINGS_DISPLAY_TITLE_TEXT = 'DISPLAY'
    SETTINGS_DISPLAY_BRIGHTNESS = 'Brightness'
    SETTINGS_DISPLAY_MODE_CLUSTER = 'Mode - Cluster:'
    SETTINGS_DISPLAY_MODE_CLUSTER_STATE_AUTO = 'Auto'
    SETTINGS_DISPLAY_MODE_CENTER_STACK = 'Mode - Center Stack:'
    SETTINGS_DISPLAY_MODE_CENTER_STACK_STATE_DAY = 'Day'
