"""
Constants for icons and text
"""


class Icons:
    SETTINGS_TOWING_BUTTON = 'settings_towing_button'
    SETTINGS_VALET_MODE_BUTTON = 'settings_valet_mode_button'
    SETTINGS_VOICE_CONTROL_BUTTON = 'settings_voice_control_button'
    SETTINGS_DISPLAY_BUTTON = 'settings_display_button'
    SETTINGS_VEHICLE_BUTTON = 'settings_vehicle_button'
    SETTINGS_SOFTWARE_UPDATES_BUTTON = 'settings_software_updates_button'
    SETIINGS_911_ASSIST_BUTTON = 'settings_911_assist_button'
    ADD_PHONE_TITLE_ICON = 'pair_bluetooth_device_title'
    APPS_FIND_MOBILE_APPS_BUTTON = 'apps_find_mobile_apps_button'
    APPS_OWNERS_MANUAL_BUTTON = 'apps_owners_manual_button'
    APPS_MOBILE_APPS_HELP_BUTTON = 'apps_mobile_apps_help_button'
    APPS_TITLE_ICON = 'apps_title'
    ARROW_DOWN_BUTTON = 'arrow_down_button'
    ARROW_DOWN_THIN_BUTTON = 'arrow_down_thin_button'
    ARROW_RIGHT_THIN_ICON = 'arrow_right_thin_icon'
    ARROW_UP_BUTTON = 'arrow_up_button'
    ARROW_UP_THIN_BUTTON = 'arrow_up_thin_button'
    AUDIO_AM_ICON = 'audio_am_icon'
    AUDIO_DELETE_ICON = 'audio_delete_icon'
    AUDIO_DIRECT_CANCEL_BUTTON_ACTIVE = 'audio_direct_cancel_button_active'
    AUDIO_DIRECT_ENTER_BUTTON_INACTIVE = 'audio_direct_enter_button_inactive'
    AUDIO_DIRECT_TUNE_BUTTON = 'audio_direct_tune_button'
    AUDIO_FM_ICON = 'audio_fm_icon'
    AUDIO_PRESET_BUTTON = 'audio_preset_button'
    AUDIO_SOURCES_AM_BUTTON = 'audio_sources_am_button'
    AUDIO_SOURCES_BLUETOOTH_BUTTON = 'audio_sources_bluetooth_stereo_button'
    AUDIO_SOURCES_FM_BUTTON = 'audio_sources_fm_button'
    AUDIO_TUNE_TOGGLE_ACTIVE = 'audio_tune_toggle_active'
    AUDIO_TUNE_TOGGLE_INACTIVE = 'audio_tune_toggle_inactive'
    BACK_BUTTON = 'back'
    BLUETOOTH_SETTINGS_CHANGE_VEHICLE_NAME_BUTTON = 'bluetooth_settings_change_vehicle_name_button'
    BLUETOOTH_SETTINGS_TITLE_ICON = 'bluetooth_settings_title'
    CLIMATE_AIR_CONDITION_INSIDE = 'climate_air_condition_inside'
    CLIMATE_CLOSE_BUTTON = 'climate_close_button'
    CLIMATE_DOWN_AIRFLOW_BUTTON = 'climate_down_airflow_button'
    CLIMATE_FRONT_HEATING_BUTTON = 'climate_front_heating_button'
    CLIMATE_MENU_ADDITIONAL_CLIMATE_CONTROLS_TITLE = 'climate_menu_additional_climate_controls_title'
    CLIMATE_MENU_BUTTON = 'climate_menu_button'
    CLIMATE_MENU_MAX_A_C_BUTTON_INACTIVE = 'climate_menu_max_a_c_button_inactive'
    CLIMATE_MENU_MAX_FRONT_HEATINGBUTTON_INACTIVE = 'climate_menu_max_front_heating_button_inactive'
    CLIMATE_PAGE_MENU_BUTTON = 'menu_button'
    CLIMATE_PAGE_PANEL_BUTTON = 'climate_page_panel_button'
    CLIMATE_REAR_HEATING_BUTTON = 'climate_rear_heating_button'
    CLIMATE_SWITCH_ON_OFF_BUTTON_ACTIVE = 'climate_switch_on_off_button_active'
    CLIMATE_UP_AIRFLOW_BUTTON = 'climate_up_airflow_button'
    CLOCK_SETTINGS_24H_DISABLE = 'mode_button_inactive'
    CLOCK_SETTINGS_24H_ENABLE = 'mode_button_active'
    CLOCK_SETTINGS_TITLE_ICON = 'clock_settings_title'
    CONNECTION_SETTINGS_BLUETOOTH_BUTTON = 'bluetooth_settings_bluetooth_button'
    CONNECTION_SETTINGS_TITLE_ICON = 'connection_settings_title'
    GENERAL_SETTINGS_BUTTON = 'settings_general_button'
    GENERAL_SETTINGS_LANGUAGE_BUTTON = 'general_settings_language_button'
    GENERAL_SETTINGS_TITLE_ICON = 'general_settings_title'
    INFO_ICON = 'info_icon'
    KEY_0_INACTIVE = 'key_0_inactive'
    KEY_1_ACTIVE = 'key_1_active'
    KEY_2_INACTIVE = 'key_2_inactive'
    KEY_3_INACTIVE = 'key_3_inactive'
    KEY_4_INACTIVE = 'key_4_inactive'
    KEY_5_INACTIVE = 'key_5_inactive'
    KEY_6_INACTIVE = 'key_6_inactive'
    KEY_7_INACTIVE = 'key_7_inactive'
    KEY_8_ACTIVE = 'key_8_active'
    KEY_9_ACTIVE = 'key_9_active'
    LANGUAGE_SETTINGS_TITLE_ICON = 'language_settings_title'
    LEFT_ARROW_BUTTON = 'arrow_left_button'
    MAIN_APPS_BUTTON_ACTIVE = 'main_apps_button_active'
    MAIN_APPS_BUTTON_INACTIVE = 'main_apps_button_inactive'
    MAIN_AUDIO_BUTTON_INACTIVE = 'main_audio_button_inactive'
    MAIN_AUDIO_BUTTON_ACTIVE = 'main_audio_button_active'
    MAIN_CLIMATE_BUTTON_ACTIVE = 'main_climate_button_active'
    MAIN_FAVORITES_BUTTON_INACTIVE = 'main_favorites_button_inactive'
    MAIN_FEATURES_BUTTON_INACTIVE = 'main_features_button_inactive'
    MAIN_NAV_BUTTON_INACTIVE = 'main_nav_button_inactive'
    MAIN_PANEL_SETTINGS_BUTTON_ACTIVE = 'main_settings_button_active'
    MAIN_PANEL_SETTINGS_BUTTON_INACTIVE = 'main_settings_button_inactive'
    MAIN_PHONE_BUTTON_ACTIVE = 'main_phone_button_active'
    MAIN_PHONE_BUTTON_INACTIVE = 'main_phone_button_inactive'
    MOBILE_APPS_SETTINGS_TITLE_ICON = 'mobile_apps_settings_title'
    MODE_BUTTON_ACTIVITY = 'mode_button_active'
    MODE_BUTTON_INACTIVITY = 'mode_button_inactive'
    OCCUPANCY_MODE_TITLE_ICON = 'occupancy_mode_title'
    PHONE_ADD_PHONE_BUTTON = 'phone_add_phone_button'
    PHONE_PAGE_ADD_PHONE_BUTTON = 'phone_add_phone_button'
    PHONE_PAGE_TITLE_ICON = 'phone_connect_phone_title'
    RADIO_SETTINGS_TITLE_ICON = 'radio_settings_title'
    RIGHT_ARROW_SLIDER = 'right_arrow'
    SETTINGS_911_STAR_ICON = 'settings_911_star_icon'
    SETTINGS_ADD_PHONE_BUTTON = 'settings_add_phone_button'
    SETTINGS_CLOCK_AM_BUTTON_INACTIVE = 'settings_clock_am_button_inactive'
    SETTINGS_CLOCK_BUTTON = 'settings_clock_button'
    SETTINGS_CLOCK_PM_BUTTON_ACTIVE = 'settings_clock_pm_button_active'
    SETTINGS_CONNECTION_SETTINGS_BUTTON = 'settings_connection_settings_button'
    SETTINGS_GENERAL_SETTINGS_BUTTON = 'settings_general_button'
    SETTINGS_MOBILE_APPS_BUTTON = 'settings_mobile_apps_button'
    SETTINGS_SYNC_NAVIGATION_BUTTON = 'settings_sync_navigation_button'
    SETTINGS_PAGE_TITLE_ICON = 'settings_title'
    SETTINGS_PAGE_VEHICLE_BUTTON = 'settings_vehicle_button'
    SETTINGS_RADIO_BUTTON = 'settings_radio_button'
    SETTINGS_SOUND_BUTTON = 'settings_sound_button'
    SETTINGS_SOUND_BALANCE_FADE_TITLE = 'settings_sound_balance_fade_title'
    SETTINGS_SOUND_BALANCE_RESET_BUTTON = 'settings_sound_balance_reset_button'
    SETTINGS_SOUND_RESET_ALL_BUTTON = 'settings_sound_tone_reset_all_button'
    SLIDER = 'slider'
    SOUND_SETTINGS_BALANCE_FADE_BUTTON = 'sound_settings_balance_fade_button'
    SOUND_SETTINGS_BUTTON = 'settings_sound_button'
    SOUND_SETTINGS_OCCUPANCY_MODE_BUTTON = 'sound_settings_occupancy_mode_button'
    SOUND_SETTINGS_RADIO_BUTTON_ACTIVE = 'radio_button_active'
    SOUND_SETTINGS_RADIO_BUTTON_INACTIVE = 'radio_button_inactive'
    SOUND_SETTINGS_SPEED_COMPENSATED_VOLUME_BUTTON = 'sound_settings_speed_compensated_volume_button'
    SOUND_SETTINGS_TITLE_ICON = 'sound_settings_title'
    SOUND_SETTINGS_TONE_SETTINGS_BUTTON = 'sound_settings_tone_settings_button'
    SPEED_COMPENSATED_VOLUME_TITLE = 'speed_compensated_volume_title'
    TONE_SETTINGS_TITLE_ICON = 'tone_settings_title'
    WIFI = 'wifi'


class Text:
    ADD_PHONE_PAGE_DISCOVER_OTHER_BUTTON_TEXT = 'Discover Other Bluetooth Devices'
    ADD_PHONE_TEXT = 'Add Phone'
    AM_TEXT = 'AM'
    APPS_PAGE_FIND_APPS_TEXT = 'Find Mobile Apps'
    APPS_PAGE_MOBILE_APPS_HELP_TEXT = 'Mobile Apps Help'
    APPS_PAGE_MOBILE_OWNERS_MANUAL_TEXT = "Owner's Manual"
    ASSIST_911_SETTINGS_BUTTON_TEXT = '911 Assist'
    AUDIO_PAGE_DIRECT_TUNE_TEXT = 'Direct Tune'
    AUDIO_PAGE_SOURCES_TEXT = 'Sources'
    AUDIO_PAGE_TITLE_TEXT = 'FM Radio'
    AUTOSET_TEXT = 'Autoset'
    BALANCE_TEXT = 'Balance'
    BLUETOOTH_SETTINGS_ADD_BLUETOOTH_DEVICE_TEXT = 'Add a Bluetooth Device'
    BLUETOOTH_SETTINGS_CHANGE_VEHICLE_NAME_TEXT = 'Change Vehicle Name'
    BLUETOOTH_SETTINGS_TITLE_TEXT = 'Bluetooth Settings'
    BLUETOOTH_STEREO_TEXT = 'Bluetooth Stereo'
    BLUETOOTH_TEXT = 'Bluetooth'
    CANCEL_TEXT = 'Cancel'
    CHANGE_VEHICLE_NAME_PAGE_TITLE_TEXT = 'Enter a vehicle name (20 char. max)'
    CLIMATE_CONTROLS_TEXT = 'Controls'
    CLIMATE_MENU_PAGE_POPUP_TITLE_TEXT = 'Additional Climate Controls'
    CLIMATE_PAGE_AC_BUTTON_TEXT = 'A/C'
    CLIMATE_PAGE_AUTO_BUTTON_TEXT = 'AUTO'
    CLIMATE_PAGE_CONTROLS_TITLE_TEXT = 'Climate Controls'
    CLIMATE_PAGE_DUAL_BUTTON_TEXT = 'DUAL'
    CLIMATE_PAGE_MAX_AC_TEXT = 'Max'
    CLIMATE_PAGE_MAX_GLASS_HEATING_TEXT = 'MAX'
    CLIMATE_PAGE_MENU_BUTTON_TEXT = 'Menu'
    CLIMATE_PAGE_BAD_CONFIGURATION_TEXT = 'IF YOU'
    CLOCK_PAGE_TITLE_TEXT = 'Clock Settings'
    CLOCK_SETTINGS_AUTO_TIME_UPDATE_TEXT = 'Auto Time Update'
    CLOCK_SETTINGS_TEXT = 'Clock'
    CLOSE_TEXT = 'Close'
    CONNECTION_SETTINGS_BUTTON_TEXT = 'Connection'
    CONNECTION_SETTINGS_MANAGE_WIFI = 'Manage Wi-Fi Networks'
    CONNECTION_SETTINGS_TITLE_TEXT = 'Connectivity'
    CONNECTION_SETTINGS_WIRELESS_APP_PROJECTION = 'Wireless App Projection'
    DIRECT_TEXT = 'Direct'
    DUAL_BUTTON_TEXT = 'DUAL'
    ENGLISH_LANGUAGE_TEXT = 'English'
    ENTER_TEXT = 'Enter'
    ENTERTAINMENT_SOURCES_TITLE_TEXT = 'Entertainment Sources'
    ESPANOL_TEXT = 'Espanol'
    FADE_TEXT = 'Fade'
    FAVORITES_TEXT = 'Favorites'
    FM_TEXT = 'FM'
    GENERAL_SETTINGS_ABOUT_SYNC_TEXT = 'About SYNC'
    GENERAL_SETTINGS_BUTTON_TEXT = 'General'
    GENERAL_SETTINGS_DISTANCE_TEXT = 'Distance'
    GENERAL_SETTINGS_SEND_FEEDBACK_TEXT = 'Send Feedback'
    GENERAL_SETTINGS_TEMPERATURE_UNITS_TEXT = 'Temperature'
    GENERAL_SETTINGS_TITLE_TEXT = 'General Settings'
    HD_TEXT = 'HD'
    HELP_TEXT = 'Help'
    HOUR_MODE_24_TEXT = '24 hour mode'
    LANGUAGE_PAGE_ENGLISH_US_TEXT = 'English (US)'
    LANGUAGE_TEXT = 'Language'
    MAIN_PANEL_APPS_TEXT = 'Apps'
    MAIN_PANEL_AUDIO_TEXT = 'Audio'
    MAIN_PANEL_CLIMATE_TEXT = 'Climate'
    MAIN_PANEL_FAVORITES_TEXT = 'Favorites'
    MAIN_PANEL_NAV_TEXT = 'Nav'
    MAIN_PANEL_PHONE_TEXT = 'Phone'
    MAIN_PANEL_SETTINGS_TEXT = 'Settings'
    MASTER_RESET_TEXT = 'Master Reset'
    MOBILE_APPS_SETTINGS_ANDROID_APPS_VIA_USB_TEXT = 'Android Apps via USB'
    MOBILE_APPS_SETTINGS_BUTTON_TEXT = 'Mobile Apps'
    MOBILE_APPS_SETTINGS_MOBILE_APPS_TEXT = 'Mobile Apps'
    MOBILE_APPS_SETTINGS_TITLE_TEXT = 'Mobile Apps Settings'
    PAIR_BLUETOOTH_DEVICE_TITLE_TEXT = 'Pair a Bluetooth Device'
    PHONE_BUTTON_TEXT = 'Add Phone'
    PHONE_CONNECT_PHONE_TITLE_TEXT = 'Connect Phone'
    PM_TEXT = 'PM'
    RADIO_BUTTON_TEXT = 'Radio'
    RADIO_SETTINGS_AUTOSET_TEXT = 'Autoset'
    RADIO_SETTINGS_RADIO_TEXT = 'Radio Text'
    RADIO_SETTINGS_REFRESH_TEXT = 'Refresh'
    RADIO_SETTINGS_TEXT = 'Text'
    RADIO_SETTINGS_TITLE_TEXT = 'Radio Settings'
    REFRESH_BUTTON_TEXT = 'Refresh'
    RESET_BALANCE_FADE_TEXT = 'Reset'
    RESET_CLOCK_GPS_TEXT = 'Reset Clock to GPS Time'
    SETTINGS_TITLE_TEXT = 'Settings'
    SOUND_SETTINGS_ALL_SEATS_TEXT = 'All Seats'
    SOUND_SETTINGS_BALANCE_FADE_TEXT = 'Balance / Fade'
    SOUND_SETTINGS_BASS_TEXT = 'Bass'
    SOUND_SETTINGS_BUTTON_TEXT = 'Sound'
    SOUND_SETTINGS_DRIVER_TEXT = 'Driver'
    SOUND_SETTINGS_FRONT_TEXT = 'Front'
    SOUND_SETTINGS_MIDRANGE_TEXT = 'Midrange'
    SOUND_SETTINGS_OCCUPANCY_MODE_TEXT = 'Occupancy Mode'
    SOUND_SETTINGS_OCCUPANCY_MODE_TITLE_TEXT = 'Occupancy Mode'
    SOUND_SETTINGS_REAR_TEXT = 'Rear'
    SOUND_SETTINGS_RESET_ALL_TEXT = 'Reset'
    SOUND_SETTINGS_SPEED_COMPENSATED_TEXT = 'Speed Compensated Volume'
    SOUND_SETTINGS_TITLE_TEXT = 'Sound Settings'
    SOUND_SETTINGS_TREBLE_TEXT = 'Treble'
    SPEED_COMPENSATED_VOLUME_PAGE_HIGH_TEXT = 'High'
    SPEED_COMPENSATED_VOLUME_PAGE_LOW_TEXT = 'Low'
    SPEED_COMPENSATED_VOLUME_PAGE_MEDIUM_TEXT = 'Medium'
    SPEED_COMPENSATED_VOLUME_PAGE_OFF_TEXT = 'Off'
    SYNC_NAVIGATION_BUTTON_TEXT = 'Sync Navigation'
    TEMPERATURE_FAHRENHEIT_TEXT = 'Fahrenheit'
    TEXT_BUTTON_0 = '0'
    TEXT_BUTTON_1 = '1'
    TEXT_BUTTON_2 = '2'
    TEXT_BUTTON_3 = '3'
    TEXT_BUTTON_4 = '4'
    TEXT_BUTTON_5 = '5'
    TEXT_BUTTON_6 = '6'
    TEXT_BUTTON_7 = '7'
    TEXT_BUTTON_8 = '8'
    TEXT_BUTTON_9 = '9'
    TONE_SETTINGS_TEXT = 'Tone Settings'
    TOUCH_SCREEN_BEEP_TEXT = 'Touch Screen Beep'


"""JIRA"""
TASK_LINK = 'https://adc.luxoft.com/jira/browse/{}'

"""DATA FOR PARAMETERIZATION"""

main_panel_images = [Icons.MAIN_AUDIO_BUTTON_INACTIVE, Icons.MAIN_CLIMATE_BUTTON_ACTIVE,
                     Icons.MAIN_PHONE_BUTTON_INACTIVE, Icons.MAIN_NAV_BUTTON_INACTIVE,
                     Icons.MAIN_APPS_BUTTON_INACTIVE, Icons.MAIN_PANEL_SETTINGS_BUTTON_INACTIVE]

audio_page_images = [Icons.AUDIO_SOURCES_FM_BUTTON, Icons.AUDIO_DIRECT_TUNE_BUTTON, Icons.AUDIO_PRESET_BUTTON,
                     Icons.AUDIO_TUNE_TOGGLE_ACTIVE, Icons.AUDIO_TUNE_TOGGLE_INACTIVE]

audio_sources_page_images = [Icons.AUDIO_SOURCES_AM_BUTTON, Icons.AUDIO_SOURCES_FM_BUTTON,
                             Icons.AUDIO_SOURCES_BLUETOOTH_BUTTON]

key_numbers_images = [Icons.KEY_0_INACTIVE, Icons.KEY_1_ACTIVE, Icons.KEY_2_INACTIVE, Icons.KEY_3_INACTIVE,
                      Icons.KEY_4_INACTIVE, Icons.KEY_5_INACTIVE, Icons.KEY_6_INACTIVE, Icons.KEY_7_INACTIVE,
                      Icons.KEY_8_ACTIVE, Icons.KEY_9_ACTIVE, Icons.AUDIO_DIRECT_ENTER_BUTTON_INACTIVE,
                      Icons.AUDIO_DIRECT_CANCEL_BUTTON_ACTIVE]

apps_page_images = [Icons.APPS_FIND_MOBILE_APPS_BUTTON,
                    Icons.APPS_OWNERS_MANUAL_BUTTON,
                    Icons.APPS_MOBILE_APPS_HELP_BUTTON]

settings_page_images = [Icons.SETTINGS_SOUND_BUTTON,
                        Icons.SETTINGS_CLOCK_BUTTON,
                        Icons.SETTINGS_CONNECTION_SETTINGS_BUTTON,
                        Icons.SETTINGS_ADD_PHONE_BUTTON,
                        Icons.SETTINGS_RADIO_BUTTON,
                        Icons.SETTINGS_SYNC_NAVIGATION_BUTTON,
                        Icons.SETTINGS_MOBILE_APPS_BUTTON,
                        Icons.SETTINGS_GENERAL_SETTINGS_BUTTON,
                        Icons.SETIINGS_911_ASSIST_BUTTON,
                        Icons.SETTINGS_SOFTWARE_UPDATES_BUTTON,
                        Icons.SETTINGS_VEHICLE_BUTTON,
                        Icons.SETTINGS_DISPLAY_BUTTON,
                        Icons.SETTINGS_VOICE_CONTROL_BUTTON,
                        Icons.SETTINGS_VALET_MODE_BUTTON,
                        Icons.SETTINGS_TOWING_BUTTON]
